### ISSUE TITLE
Instruction on how to use it?

### ISSUE THREAD

**Issue by ewerlopes** [mandt-lab/dynamic-word-embeddings#1]
HI, 

Could you please point out instruction on how to use it? Perhaps an example with some input files?

Awesome work!
Thanks.

**Comment by ewerlopes** [comment]
Oh! It seems some instructions are located in the Shell folder.

**Comment by aodongli** [comment]
Hi,

Thanks for tuning in! We are still working on the code and example. It may take some time. We will upload some examples when it is finished.

**Comment by ewerlopes** [comment]
Thank you!
